#!/usr/bin/bash

dir="/home/ramo/Music/"

output=$(mpc -f "%title%\n%artist%\n%album%\n%file%" current)
if [ $? -ne 1 ]
then
	i=1
	while read -r line; do
		array[$i]="$line"
		(( i++ ))
	done <<< "$output"

	array[1]=$(echo "${array[1]}" | sed s/\&/\&amp\;/)
	array[2]=$(echo "${array[2]}" | sed s/\&/\&amp\;/)
	array[3]=$(echo "${array[3]}" | sed s/\&/\&amp\;/)

	file=$(ls -t "$(dirname "$dir${array[4]}")"/*.{jpg,png} 2> /dev/null | head -n 1)

	echo $file

	notify-send "${array[1]}" "${array[2]} - ${array[3]}" -t 4000 -i "$file"
fi
